### ISSUE TITLE
Supported CPU ISA

### ISSUE THREAD

**Issue by nstarke** [ChrisTheCoolHut/Firmware_Slap#14]
Hello,
Does Firmware Slap support MIPS? I ask because I ran a few MIPS binaries through and received no results when I know for a fact there are various vulnerable functions in the firmware binary.  Is there anything special I would need to do or develop to make MIPS works?  

I do see this after every function trace worker thread:
```
<SimulationManager with all stashes empty (1 errored)>
```

I'm not sure if that is relevant or not.

Thanks for your help!

**Comment by ChrisTheCoolHut** [comment]
Hey @nstarke, 

it does!

Firmware Slap is using [angr](angr.io) to do it's lifting and concolic analysis. angr supports mips, however Firmware Slap is not guaranteed to find all vulnerabilities.

I've designed it to detect basic memory corruptions and command injection vulnerabilities. There are also resource time outs. If you think it needs more time or resources to analyze take a look at Discover and Dumps on line [212](https://github.com/ChrisTheCoolHut/Firmware_Slap/blob/5c5d2d1cdf554aef3fbe58e0fc6b69d8e9f716eb/bin/Discover_And_Dump.py#L212)

Change the timeout and memory limit values to larger values.
```
            time_limit=60,
            worker_max_memory_per_child=2048000)
```

**Comment by nstarke** [comment]
Thank you, I will try that.  Closing now.
