### ISSUE TITLE
KeyError: 'DATA_ADDRS'

### ISSUE THREAD

**Issue by mluis** [ChrisTheCoolHut/Firmware_Slap#22]
I'm getting this stack trace while running:

`python Vuln_Cluster_Celery.py -V load.pickle -L lib_mix/ folder/`

```
Traceback (most recent call last):
  File "Vuln_Cluster_Celery.py", line 210, in <module>
    main()
  File "Vuln_Cluster_Celery.py", line 116, in main
    print_function(bugs[0])
  File "Vuln_Cluster_Celery.py", line 187, in print_function
    colored("\tMemory load addr {}".format(mem_val['DATA_ADDRS'][0]),
KeyError: 'DATA_ADDRS'
```

It seems that DATA_ADDRS doesn't exist. Don't know exactly what may be causing this.

**Comment by ChrisTheCoolHut** [comment]
Thanks for the issue @mluis 

I swapped the print function to the one in ghidra_handler that checks for the existence of the key.

95f6897
