### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by nstarke** [ChrisTheCoolHut/Firmware_Slap#3]
How can I convert `Vulnerable_Pickle` to JSON formatted data?  I tried basic conversion techniques and received error messages saying `AsyncResult not serializable`.  Thanks in advance.

**Comment by ChrisTheCoolHut** [comment]
Thanks for the Issue, I just pushed up a change.

You'll get two pickles and json files representing the analyzed files.

`Discover_And_Dump.py examples/iwconfig -D iwconfig_results`

```
$ ls iwconfig_results.*
iwconfig_results.all.json  iwconfig_results.all.pickle  iwconfig_results.json  iwconfig_results.pickle
```


c637676

**Comment by nstarke** [comment]
Thank you!!!!
