### ISSUE TITLE
Function handler import bug

### ISSUE THREAD

**Issue by nitzan83** [ChrisTheCoolHut/Firmware_Slap#31]
https://github.com/ChrisTheCoolHut/Firmware_Slap/blob/a68b45622af2850e4817addc6814760dfeab523b/bin/Vuln_Discover_Celery.py#L68

In this line you should import without the `as fh` in the end

**Comment by mmiszczyk** [comment]
You're right, I made a mistake in this script. Made a PR to fix it.
