### ISSUE TITLE
Quickstart Additional Note

### ISSUE THREAD

**Issue by dustingraham** [ChrisTheCoolHut/Firmware_Slap#6]
Consider adding a note in the section about installing Ghidra to ensure that Ghidra works. In our experience it fails to gather functions if a JDK is not installed with a fairly non-informational error message

```Failed to get function information for file Firmware_Slap/examples/upload.cgi```

May also consider something in the setup.sh could run some basic check to ensure Ghidra is functional.

I figured this out once I tried to run ghidra.

```
$ ghidraDebug 
Java runtime not found.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
```

Installing default-jdk on my ubuntu box then got past the function information.

**Comment by ChrisTheCoolHut** [comment]
Thank you, that can be a pretty invisible error.

I added a note to the README in c63767630516ebb11edebf4ca65de5614fadf64b
