### ISSUE TITLE
Absolute Path

### ISSUE THREAD

**Issue by dustingraham** [ChrisTheCoolHut/Firmware_Slap#7]
Still working on turning the knobs and dials to understand how this is working. Most of the binaries I want to analyze are not *.cgi files, they don't have any extensions, so the `Pwn_Firmware_CGI.py` doesn't work. But, I may try adjusting the cgi extension check and just checking everything... that might cause it to check too many files.

As I was looking through the code, I also noticed:

https://github.com/ChrisTheCoolHut/Firmware_Slap/blob/master/bin/Pwn_Firmware_CGI.py#L214

```
        ld_path="/home/chris/Tools/firmware_slap/Almond_Root/lib"
```

That should probably be a relative path? I'd create another PR but I'm not confident what it should be.

**Comment by ChrisTheCoolHut** [comment]
`Discover_And_Dump.py` should do what you want. LD_PATH is a optional parameter passed in when looking at firmware and the libraries required by the binaries being analyzed are not the same architecture as your host systems.

Also oops on the hardcoded path

15d5011956b695453167c1a401d20e5040d766f5
