### ISSUE TITLE
Celery error when running Discover and dump

### ISSUE THREAD

**Issue by nstarke** [ChrisTheCoolHut/Firmware_Slap#9]
when i run `Discover and dump` against a firmware binary, i receive the following error in the celery process:

```
KeyError: 'firmware_slap.celery_tasks.async_trace_func'
[2019-08-13 13:56:43,760: ERROR/MainProcess] Received unregistered task of type 'firmware_slap.celery_tasks.async_trace_func'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

```

Any ideas on why this might be happening? Thanks for your help!

**Comment by ChrisTheCoolHut** [comment]
Are you running `celery -A firmware_slap.celery_tasks worker --loglevel=info` out of the main Firmware_Slap folder?

When you first run celery it should tell you which tasks are registered, which functions does it show?

**Comment by nstarke** [comment]
I was running the celery command out of the build dir.  That seems to be my problem.  I will submit a PR with README.md updates in a few hours.  Thanks!

**Comment by nstarke** [comment]
With that last merge, I think we can close this issue.
